apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: "2026-03-19T09:41:42Z"
  labels:
    app: mongodb
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/part-of: workshop
    app.openshift.io/runtime-version: 6.0.4
  name: mongodb
  namespace: wksp-user1
  resourceVersion: "427469"
  uid: 0c491ffe-f1c3-49dc-a088-c02c5f8b6680
spec:
  clusterIP: 172.231.147.59
  clusterIPs:
  - 172.231.147.59
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 27017-tcp
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb
    deployment: mongodb
  sessionAffinity: None
  type: ClusterIP