apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: "2026-03-19T11:53:52Z"
  labels:
    app: parksmap
    app.kubernetes.io/component: parksmap
    app.kubernetes.io/instance: parksmap
    app.kubernetes.io/name: parksmap
    app.kubernetes.io/part-of: workshop
    app.openshift.io/runtime-version: latest
  name: parksmap
  namespace: wksp-user1
  resourceVersion: "523885"
  uid: 7714a70c-c60b-4ab2-8dab-8b8aa2048aef
spec:
  clusterIP: 172.231.183.189
  clusterIPs:
  - 172.231.183.189
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: parksmap
    deployment: parksmap
  sessionAffinity: None
  type: ClusterIP