apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  creationTimestamp: "2026-03-19T11:55:59Z"
  generation: 1
  labels:
    app: parksmap
    app.kubernetes.io/component: parksmap
    app.kubernetes.io/instance: parksmap
    app.kubernetes.io/name: parksmap
    app.kubernetes.io/part-of: workshop
    app.openshift.io/runtime-version: latest
  name: parksmap
  namespace: wksp-user1
  resourceVersion: "525440"
  uid: ae6ec6a1-a0e8-4f39-86ca-81fbcef8afcb
spec:
  host: parksmap-wksp-user1.apps.cluster-m4xv6.dynamic.redhatworkshops.io
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
  to:
    kind: Service
    name: parksmap
    weight: 100
  wildcardPolicy: None